# Generated by Django 5.2.5 on 2025-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=350)),
                ('image', models.ImageField(upload_to='TipsImages')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
