# Generated by Django 5.2.5 on 2025-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_healthtips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtips',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
