# Generated by Django 5.2.5 on 2025-09-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_alter_appointment_slot'),
        ('doctor', '0004_prescription_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Patient.appointment'),
        ),
    ]
