# Generated by Django 5.2.5 on 2025-08-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Policy_number', models.CharField(max_length=50)),
                ('Policy_holder', models.CharField(max_length=50)),
                ('Plan_type', models.CharField(choices=[('PPO', 'PPO'), ('MMO', 'MMO'), ('Medicare', 'Medicare')], max_length=50)),
                ('Policy_date', models.DateField()),
                ('Insurance_img', models.ImageField(upload_to='insuranceImg/')),
                ('Verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='Patient.patient')),
            ],
        ),
    ]
