# Generated by Django 5.2.5 on 2025-09-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_availableslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment_request',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='Patient.appointment'),
        ),
    ]
