# Generated by Django 5.2.5 on 2025-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_timeslot_availableslot_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
