# Generated by Django 5.2.5 on 2025-09-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_availableslot_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinmentSlot', to='Patient.availableslot', unique=True),
        ),
    ]
