# Generated by Django 5.2.5 on 2025-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_appointment_is_paid_patientinsurance_copay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='had_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
