# Generated by Django 5.2.5 on 2025-09-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_alter_appointment_slot'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Request', to='Patient.patient')),
            ],
        ),
    ]
