# Generated by Django 5.2.5 on 2025-09-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patient_had_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='appoinment_request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
