# Generated by Django 5.2.5 on 2025-09-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_appoinment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment_request',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('pending', 'pending'), ('rescheduled', 'rescheduled')], default='pending', max_length=20),
        ),
    ]
