# Generated by Django 5.2.5 on 2025-09-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Patient.appoinment_request'),
        ),
    ]
