# Generated by Django 5.2.5 on 2025-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_alter_payments_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
