# Generated by Django 5.2.5 on 2025-09-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_alter_payments_stripe_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinsurance',
            name='copay_amount',
        ),
    ]
