# Generated by Django 5.2.5 on 2025-10-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_remove_patientinsurance_copay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_request',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('pending', 'pending'), ('rescheduled', 'rescheduled'), ('cancel', 'cancel')], default='pending', max_length=20),
        ),
    ]
