# Generated by Django 5.2.5 on 2025-10-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0012_alter_appoinment_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appoinmentSlot', to='Patient.availableslot', unique=True),
        ),
    ]
